name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repositorio
          uses: actions/checkout@v6

        - name: welcome message
          run: |
               echo "My First GitHub Actions Workflow"
               ls -ltra
               cat README.md

        #to - name: List files
        #  run: ls 

        #- name: Read file
        #  run: cat README.md